# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='administrativedivision',
            name='administrative_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='administrative_division.AdministrativeLevel'),
        ),
        migrations.AddField(
            model_name='administrativedivision',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrative_division.AdministrativeDivision'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativedivision',
            unique_together=set([('name', 'administrative_level')]),
        ),
    ]
