# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_division', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Administrative Division'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Administrative Level'),
        ),
    ]
