# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_division', '0002_auto_20180126_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='administrative_division.AdministrativeDivision'),
        ),
        CreateExtension('postgis'),
    ]
