# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_division', '0003_auto_20180130_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedivision',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='administrativedivision',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
    ]
