# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 09:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_division', '0004_auto_20180222_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativedivision',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='administrativedivision',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
