# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('manifacture_year', models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, null=True, verbose_name='Manifacture Year')),
                ('engine_volume', models.FloatField(null=True, verbose_name='Engine Volume')),
                ('mileage', models.CharField(max_length=255, null=True, verbose_name='Mileage')),
                ('steering', models.CharField(choices=[('слева', 'слева'), ('справа', 'справа')], default='слева', max_length=255, null=True, verbose_name='Steering')),
                ('metallic', models.BooleanField(default=False, verbose_name='Metallic')),
                ('customs_cleared', models.BooleanField(default=False, verbose_name='Customs cleared')),
                ('state', models.CharField(choices=[('на ходу', 'на ходу'), ('не на ходу', 'не на ходу'), ('аварийный', 'аварийный')], max_length=255, null=True, verbose_name='State')),
                ('drive', models.CharField(choices=[('передний', 'передний'), ('задний', 'задний'), ('полный', 'полный')], max_length=255, null=True, verbose_name='Drive')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.product', models.Model),
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_kk', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('make', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='carmodel', to='transports.CarMake')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('productimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ProductImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productimage',),
        ),
        migrations.AddField(
            model_name='car',
            name='body',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarBody'),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarMake'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.Transmission'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set([('make', 'code')]),
        ),
    ]
