# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('mark', models.CharField(max_length=255)),
                ('rear_type', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('products.product',),
        ),
    ]
