# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180122_1746'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('productimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ProductImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.productimage',),
        ),
    ]
