# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbody',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='carmake',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='carbody',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carbody',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carbody',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='customs_cleared',
            field=models.BooleanField(verbose_name='Customs cleared'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('передний', 'передний'), ('задний', 'задний'), ('полный', 'полный')], max_length=255, verbose_name='Drive'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(verbose_name='Engine Volume'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manifacture_year',
            field=models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='Manifacture Year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='metallic',
            field=models.BooleanField(default=False, verbose_name='Metallic'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=255, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('на ходу', 'на ходу'), ('не на ходу', 'не на ходу'), ('аварийный', 'аварийный')], max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering',
            field=models.CharField(choices=[('слева', 'слева'), ('справа', 'справа')], default='слева', max_length=255, verbose_name='Steering'),
        ),
    ]
