# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_bargain'),
        ('transports', '0002_auto_20180206_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='car',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='car',
            name='transport_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transports.Transport'),
            preserve_default=False,
        ),
    ]
