# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_make_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('make', 'code')]),
        ),
    ]
