# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_auto_20180123_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarBody'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.Color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarMake'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.CarModel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transports.Transmission'),
        ),
    ]
