# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0007_auto_20180123_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
    ]
