# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:01
from __future__ import unicode_literals

import auction_api.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('name_en', models.CharField(max_length=255, null=True, unique=True)),
                ('name_kk', models.CharField(max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to=auction_api.categories.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
