# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180124_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
