# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20180128_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
