# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:59
from __future__ import unicode_literals

import auction_api.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20180122_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=auction_api.categories.models.user_directory_path),
        ),
    ]
