# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20180129_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.Category'),
        ),
    ]
