# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180123_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True, blank=True),
            preserve_default=False,
        ),
    ]
