# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20180123_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
