# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

import auction_api.ad_banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Advertisement Banner')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('image', models.ImageField(upload_to=auction_api.ad_banners.models.user_directory_path, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
