# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-16 08:48
from __future__ import unicode_literals

import auction_api.ad_banners.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.CharField(max_length=255, verbose_name='Advertisement Banner')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner')),
                ('image', models.ImageField(upload_to=auction_api.ad_banners.models.user_directory_path, verbose_name='Image')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_banners_adbanner_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
