# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Advertisement Banner'),
        ),
    ]
