# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRadius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField()),
                ('metric', models.CharField(choices=[('км', 'км')], max_length=255)),
            ],
        ),
    ]
