# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 13:16
from __future__ import unicode_literals

import auction_api.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180228_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=auction_api.products.models.user_directory_path),
        ),
    ]
