# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180122_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productimage_related', to='products.Product'),
        ),
    ]
