# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0006_auto_20180126_1531'),
        ('products', '0004_auto_20180124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bargain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bargains.Bargain'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.Color'),
        ),
    ]
