# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-12 12:46
from __future__ import unicode_literals

import auction_api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=auction_api.users.models.user_directory_path),
        ),
    ]
