# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='End Date')),
                ('start_price', models.IntegerField(verbose_name='Start Price')),
                ('current_price', models.IntegerField(verbose_name='Current Price')),
                ('name', models.CharField(max_length=255, verbose_name='Bargain Name')),
                ('description', models.TextField(default=None, verbose_name='Bargain Description')),
                ('seen', models.IntegerField(verbose_name='Seen')),
                ('on_top', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-on_top', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='BargainBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BargainComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BargainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('name', models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type')),
                ('name_ru', models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type')),
                ('name_en', models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type')),
                ('name_kk', models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
