# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bargains', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargaintype',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bargains_bargaintype_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargaintype',
            name='updated_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='bargain_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bargains.BargainType'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bargains_bargain_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='updated_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
