# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bargains', '0001_initial'),
        ('administrative_division', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargaintype',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains_bargaintype_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargaintype',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargaincomment',
            name='bargain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bargains.Bargain'),
        ),
        migrations.AddField(
            model_name='bargaincomment',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains_bargaincomment_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargaincomment',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='bargain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bargains.Bargain'),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains_bargainbet_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargain_addresses', to='administrative_division.AdministrativeDivision'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='bargain_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bargains.BargainType'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='comments',
            field=models.ManyToManyField(related_name='bargain_comments', through='bargains.BargainComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains_bargain_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='participants',
            field=models.ManyToManyField(related_name='bargains', through='bargains.BargainBet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='product',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
