# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0002_auto_20180228_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bargain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bargain',
            name='name',
        ),
    ]
