# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 11:02
from __future__ import unicode_literals

import auction_api.bargains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0002_auto_20180122_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='image',
            field=models.ImageField(upload_to=auction_api.bargains.models.user_directory_path),
        ),
    ]
