# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20180123_1902'),
        ('bargains', '0004_auto_20180123_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargainProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bargain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bargain_products', to='bargains.Bargain')),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bargains_bargainproducts_related', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.Product')),
                ('updated_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bargain',
            name='products',
            field=models.ManyToManyField(through='bargains.BargainProducts', to='products.Product'),
        ),
    ]
