# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 08:57
from __future__ import unicode_literals

import auction_api.bargains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0004_auto_20180124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargaintype',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Bargain Type'),
        ),
        migrations.AddField(
            model_name='bargaintype',
            name='name_kk',
            field=models.TextField(null=True, verbose_name='Bargain Type'),
        ),
        migrations.AddField(
            model_name='bargaintype',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Bargain Type'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='image',
            field=models.ImageField(upload_to=auction_api.bargains.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Bargain Name'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='seen',
            field=models.IntegerField(verbose_name='Seen'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Start Price'),
        ),
        migrations.AlterField(
            model_name='bargaintype',
            name='name',
            field=models.TextField(verbose_name='Bargain Type'),
        ),
    ]
