# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bargains', '0005_auto_20180126_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargainBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bargainproducts',
            name='bargain',
        ),
        migrations.RemoveField(
            model_name='bargainproducts',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bargainproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bargainproducts',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bargain',
            name='products',
        ),
        migrations.AlterField(
            model_name='bargain',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains', to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='BargainProducts',
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='bargain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bargains.Bargain'),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargains_bargainbet_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargainbet',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargain',
            name='participants',
            field=models.ManyToManyField(through='bargains.BargainBet', to=settings.AUTH_USER_MODEL),
        ),
    ]
