# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0007_auto_20180126_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 16, 27, 58, 237800), verbose_name='End Date'),
        ),
    ]
