# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0008_auto_20180126_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 18, 36, 50, 292892), verbose_name='End Date'),
        ),
    ]
