# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0018_auto_20180130_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 8, 33, 42, 41400, tzinfo=utc), verbose_name='End Date'),
        ),
    ]
