# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0019_auto_20180130_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End Date'),
        ),
    ]
