# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0020_auto_20180130_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='bargain_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bargains.BargainType'),
        ),
        migrations.AlterField(
            model_name='bargaintype',
            name='name',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type'),
        ),
        migrations.AlterField(
            model_name='bargaintype',
            name='name_en',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type'),
        ),
        migrations.AlterField(
            model_name='bargaintype',
            name='name_kk',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type'),
        ),
        migrations.AlterField(
            model_name='bargaintype',
            name='name_ru',
            field=models.TextField(default=None, null=True, unique=True, verbose_name='Bargain Type'),
        ),
    ]
