# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0021_auto_20180130_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargain',
            name='description',
            field=models.TextField(default=None, verbose_name='Bargain Description'),
        ),
    ]
