# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 09:10
from __future__ import unicode_literals

import auction_api.bargains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0022_bargain_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=auction_api.bargains.models.user_directory_path, verbose_name='Image'),
        ),
    ]
