# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_bargain'),
        ('bargains', '0023_auto_20180201_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargain',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product', null=True),
        ),
    ]
