# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0026_auto_20180221_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargain',
            name='on_top',
            field=models.BooleanField(default=False),
        ),
    ]
